workflows:
  react_native_android:
    name: Build Android Only
    max_build_duration: 60
    environment:
      node: 18.16.0
      npm: 9.5.1
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android release APK
        script: |
          cd android && ./gradlew assembleRelease && cd ..
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your.email@example.com   # Replace with your email
