workflows:
  my-workflow:
    name: My Node.js Web App Workflow
    instance_type:
    max_build_duration: 60
    environment:
      node: latest
      npm: latest
    scripts:
      - npm install
      - npm run build
    artifacts:
      - build/**


